### ISSUE TITLE
Firefox don't work

### ISSUE THREAD

**Issue by marcandreher** [MarcPlaying/shiina-web#1]
Doesn't launch https://cdn.discordapp.com/attachments/552524145917689881/554039771161296906/unknown-17.png

**Comment by mellowagain** [comment]
This is because you're setting your MIME Type to a webp. 

Sent `Content-Type` header by `next.enjuu.click` has the following content: `text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`

Firefox reads the last MIME type specified, which in this case is `image/webp`. So it interprets it as webp, even thought it isn't.

![image](https://user-images.githubusercontent.com/24739711/54077630-5aba7f00-42bb-11e9-92dd-5f568aa7de18.png)
